### ISSUE TITLE
Laravel 4.2: extra line break at the start of the file

### ISSUE THREAD

**Issue by rombat** [dwightwatson/sitemap#17]
Hi,
Chrome displays this error when I try to access to my sitemap:
```
This page contains the following errors:

error on line 2 at column 6: XML declaration allowed only at the start of the document
```
The thing is, I have an extra line break before the xml opening tag:
```

<?xml version="1.0" encoding="UTF-8"?><urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
```

My sitemap is generated through a controller and I have a route like this:
```Route::get('sitemap', 'SitemapController@index');```

The weird thing is that if i generate my sitemap directly from the route, there's no error:

```
Route::get('tests', function() {
    Sitemap::addTag(route('home'));
    return Sitemap::renderSitemap();
});
```

**Comment by dwightwatson** [comment]
I cannot replicate this with a fresh copy of Laravel 4.2. The fact is only occurs when you are routing through a controller suggests to me you've got an empty space outside of a PHP code block somewhere in your code. Check the top of your classes to ensure you haven't got an empty line or a blank space before the opening `<?php` tag (your code editor can probably help you with this). The logic in this package doesn't work any differently from a controller or normal route, so that wouldn't explain the difference in the output.

**Comment by rombat** [comment]
I found out where the problem was from.
I had a php closing tag in my BaseController.
Removed it, fixed it.
Thanks anyway.
