### ISSUE TITLE
Namespace declaration missing for multilingual tags

### ISSUE THREAD

**Issue by rspahni** [dwightwatson/sitemap#44]
Thanks for a great package. When using the multilingual tags option, the xhtml namespace should be added in the xml header like so: `xmlns:xhtml="http://www.w3.org/1999/xhtml"`. You have similar logic in place in sitemap.php for image tags. Actually, I have not submitted a PR as I am not totally sure how to best make this conditional on `$__tag instanceof \Watson\Sitemap\Tags\MultilingualTag`.

**Comment by dwightwatson** [comment]
Hey, thanks for reporting this. I've just pushed an update on the `master` branch that will add that namespace to the XML tag if any of the tags present in the sitemap are `MultilingualTag`. Please let me know if that's correct, and if you have a chance test it out. Otherwise I'll tag a new release in a day or two.

**Comment by rspahni** [comment]
Works like a charm! Not using PHPUnit, so cannot provide the evidence. One small thing: Two whitespaces within the urlset tag separating the two xmlns items (probably the same for the image one): `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"  xmlns:xhtml="http://www.w3.org/1999/xhtml">` Since it's XML, it may be worthwhile paying attention to such minor details.  :)  thanks for the ultra swift response & merry Xmas !!!

**Comment by dwightwatson** [comment]
Good call - I've patched that up too. I'll push out a new tagged release now. Merry Christmas to you too!
