### ISSUE TITLE
Cache options

### ISSUE THREAD

**Issue by adampatterson** [dwightwatson/sitemap#51]
I have been running into some issues while making a sitemap from 10,000 records pulled from an API.

I would like to cache the sitemap as a file rather than using my apps default cache Memcached.

Ideally, I can choose what to do with the file ( local, S3 )

Doing this lets me setup a process to generate the file rather than letting Google wait for it.

**Comment by dwightwatson** [comment]
I think this might be better handled in your app rather than the package. I totally understand the need for more something more advanced here, especially if you're going to drop the file to disk and let your server serve it out directly.

You should be able to call `Sitemap::xml()` to get the raw XML of your sitemap and then you can choose to do whatever you like with it, like writing it out to a file. Hope this helps!

**Comment by adampatterson** [comment]
Perfect! 

Call `Sitemap::xml()` over `Sitemap::render()`?

**Comment by dwightwatson** [comment]
From memory, `Sitemap::render()` returns a full Laravel response object which you wouldn't want to write to a file. I think we cache that under the hood for the internal caching because it's faster than having to rebuild the response object on every request.

If you wanted to write to a file I'd go `Sitemap::xml()` because you're then getting just the sitemap content, not the response object.
